import = [
    "~/.config/alacritty/themes/nightfox.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[shell]
program = "/usr/bin/fish"
