import = [
    "~/.config/alacritty/themes/rose-pine.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
